apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticwebsite
  labels:
    app: staticwebsite
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: staticwebsite
  template:
    metadata: 
      lables:
        app: staticwebsite
    spec:
      container:
        -name: staticwebsite
         image= sheetalsshetty/finallabexam:v1
         port= 80
    
