apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticwebsite
  labels:
    app: staticwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staticwebsite
  template:
    metadata: 
      labels:
        app: staticwebsite
    spec:
      container:
        -name: staticwebsite
        label:
          app: staticwebsite
        image: sheetalsshetty/finallabexam:v1
        port: 80
    
