apiVersion: v1
kind: Service
metadata:
  name: staticweb
  labels:
    app: staticweb
spec:
  type: NodePort
  selector:
    app: staticweb
  ports:
    - port: 83       
      targetPort: 80  
   
    
