apiVersion: app/v1
kind: Service
metadata: 
  name: staticwebsite
  labels:
    app: staticwebsite
spec:
  type: NodePort
  selector: 
    label: staticwebsite
  ports:
    port: 83
    targetPort: 80
    
